default_title: "Coding towards less WTF" 
meta_keywords: "foundation, html5, css3, jquery, portfolio, creative, design, personal"
meta_description: "Miles Starkenburg's Professional Portfolio"
meta_author: "Miles Starkenburg"
meta_viewport: "width=device-width,initial-scale=1.0"
